title: KissServer
description: Tiny zero-dependency Java 17+ HTTP/1.1 server library for simple REST-style applications.
url: "https://arthurhoch.github.io"
baseurl: "/kiss-server"
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
