title: KissServer
description: A tiny, zero-dependency Java 17+ HTTP/1.1 socket server library.
url: "https://arthurhoch.github.io"
baseurl: "/kiss-server"
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
